# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: ONION
description: The professional publishing platform
cover: https://postfiles.pstatic.net/MjAxNzEyMTdfMjc5/MDAxNTEzNTE4MDkyMzY4.oomDWLAMWHDv94TUfikjTZ_yoZXEQ3oAGvxRajhwDI4g.3cder0b4gUGXIMshgSAKXa26njoeOfWhvNu-YNHOARIg.PNG.lsa_sss/image.png?type=w966
logo: http://postfiles8.naver.net/MjAxNzEyMTdfOCAg/MDAxNTEzNTE3MzM5NzIw.-N4wo3TsB8V2fte0Flsz7LjZ6itC9nm_GdX9b9I7kSgg.bFvXXEel9gzYkuCpF533noiPCk3hS-l5a1pNqnFDmuUg.PNG.lsa_sss/sns.png?type=w966
logo_dark: https://postfiles.pstatic.net/MjAxNzEyMTdfMjc5/MDAxNTEzNTE4MDkyMzY4.oomDWLAMWHDv94TUfikjTZ_yoZXEQ3oAGvxRajhwDI4g.3cder0b4gUGXIMshgSAKXa26njoeOfWhvNu-YNHOARIg.PNG.lsa_sss/image.png?type=w966
favicon: assets/images/favicon.png
production_url: https://myJekyll.github.io/jasper2/
source_url: https://github.com/myJekyll/jasper2/

# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: tryghost # replace by your username
facebook: ghost # replace by your username

# Disqus
disqus: False
disqus_name: myjekyll # replace by your username

# Google Analytics
google_analytics: UA-69281367-1 # replace by your GA id

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]
exclude: [vendor]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: myJekyll
repo: jasper2
branch: master
relative_source: ../jasper2/
destination: ../jasper2-pages/
production_url:  https://myJekyll.github.io/jasper2/
source_url:  https://github.com/myJekyll/jasper2/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
